package dpp.valuemaps;

import java.util.HashMap;
import java.util.Map;

public class Iso_639_2_Map extends BaseTypeMap {

	protected Map<String, String> mapOfLanguageCodesToNames = new HashMap<String, String>();

	public Iso_639_2_Map() {
		super();
		mapOfLanguageCodesToNames.put("aar", "Afar");
		mapOfLanguageCodesToNames.put("abk", "Abkhazian");
		mapOfLanguageCodesToNames.put("ace", "Acehnese, Achinese");
		mapOfLanguageCodesToNames.put("ach", "Acoli");
		mapOfLanguageCodesToNames.put("ada", "Adangme");
		mapOfLanguageCodesToNames.put("ady", "Adyghe, Adygei");
		mapOfLanguageCodesToNames.put("afa", "Afroasiatic languages");
		mapOfLanguageCodesToNames.put("afh", "Afrihili");
		mapOfLanguageCodesToNames.put("afr", "Afrikaans");
		mapOfLanguageCodesToNames.put("ain", "Ainu (Japan)");
		mapOfLanguageCodesToNames.put("aka", "Akan");
		mapOfLanguageCodesToNames.put("akk", "Akkadian");
		mapOfLanguageCodesToNames.put("alb", "Albanian");
		mapOfLanguageCodesToNames.put("sqi", "Albanian");
		mapOfLanguageCodesToNames.put("ale", "Aleut");
		mapOfLanguageCodesToNames.put("alg", "Algonquian languages");
		mapOfLanguageCodesToNames.put("alt", "Southern Altai");
		mapOfLanguageCodesToNames.put("amh", "Amharic");
		mapOfLanguageCodesToNames.put("ang", "Old English (c. 450�1100)");
		mapOfLanguageCodesToNames.put("anp", "Angika");
		mapOfLanguageCodesToNames.put("apa", "Apache languages");
		mapOfLanguageCodesToNames.put("ara", "Arabic");
		mapOfLanguageCodesToNames.put("arc", "Official Aramaic, Imperial Aramaic (700 BC�300 BC)");
		mapOfLanguageCodesToNames.put("arg", "Aragonese");
		mapOfLanguageCodesToNames.put("arm", "Armenian");
		mapOfLanguageCodesToNames.put("hye", "Armenian");
		mapOfLanguageCodesToNames.put("arn", "Mapudungun, Mapuche");
		mapOfLanguageCodesToNames.put("arp", "Arapaho");
		mapOfLanguageCodesToNames.put("art", "Artificial languages");
		mapOfLanguageCodesToNames.put("arw", "Arawak");
		mapOfLanguageCodesToNames.put("asm", "Assamese");
		mapOfLanguageCodesToNames.put("ast", "Asturian, Bable, Leonese, Asturleonese");
		mapOfLanguageCodesToNames.put("ath", "Athabaskan languages");
		mapOfLanguageCodesToNames.put("aus", "Australian languages");
		mapOfLanguageCodesToNames.put("ava", "Avaric");
		mapOfLanguageCodesToNames.put("ave", "Avestan");
		mapOfLanguageCodesToNames.put("awa", "Awadhi");
		mapOfLanguageCodesToNames.put("aym", "Aymara");
		mapOfLanguageCodesToNames.put("aze", "Azerbaijani");
		mapOfLanguageCodesToNames.put("bad", "Banda languages");
		mapOfLanguageCodesToNames.put("bai", "Bamileke languages");
		mapOfLanguageCodesToNames.put("bak", "Bashkir");
		mapOfLanguageCodesToNames.put("bal", "Baluchi");
		mapOfLanguageCodesToNames.put("bam", "Bambara");
		mapOfLanguageCodesToNames.put("ban", "Balinese");
		mapOfLanguageCodesToNames.put("baq", "Basque");
		mapOfLanguageCodesToNames.put("eus", "Basque");
		mapOfLanguageCodesToNames.put("bas", "Basa");
		mapOfLanguageCodesToNames.put("bat", "Baltic languages");
		mapOfLanguageCodesToNames.put("bej", "Beja, Bedawiyet");
		mapOfLanguageCodesToNames.put("bel", "Belarusian");
		mapOfLanguageCodesToNames.put("bem", "Bemba");
		mapOfLanguageCodesToNames.put("ben", "Bengali");
		mapOfLanguageCodesToNames.put("ber", "Berber languages");
		mapOfLanguageCodesToNames.put("bho", "Bhojpuri");
		mapOfLanguageCodesToNames.put("bih", "Bihari languages");
		mapOfLanguageCodesToNames.put("bik", "Bikol");
		mapOfLanguageCodesToNames.put("bin", "Bini, Edo");
		mapOfLanguageCodesToNames.put("bis", "Bislama");
		mapOfLanguageCodesToNames.put("bla", "Siksika");
		mapOfLanguageCodesToNames.put("bnt", "Bantu languages");
		mapOfLanguageCodesToNames.put("bos", "Bosnian");
		mapOfLanguageCodesToNames.put("bra", "Braj");
		mapOfLanguageCodesToNames.put("bre", "Breton");
		mapOfLanguageCodesToNames.put("btk", "Batak languages");
		mapOfLanguageCodesToNames.put("bua", "Buriat");
		mapOfLanguageCodesToNames.put("bug", "Buginese");
		mapOfLanguageCodesToNames.put("bul", "Bulgarian");
		mapOfLanguageCodesToNames.put("bur", "Burmese");
		mapOfLanguageCodesToNames.put("mya", "Burmese");
		mapOfLanguageCodesToNames.put("byn", "Blin, Bilin");
		mapOfLanguageCodesToNames.put("cad", "Caddo");
		mapOfLanguageCodesToNames.put("cai", "Central American Indian languages");
		mapOfLanguageCodesToNames.put("car", "Galibi Carib");
		mapOfLanguageCodesToNames.put("cat", "Catalan, Valencian");
		mapOfLanguageCodesToNames.put("cau", "Caucasian languages");
		mapOfLanguageCodesToNames.put("ceb", "Cebuano");
		mapOfLanguageCodesToNames.put("cel", "Celtic languages");
		mapOfLanguageCodesToNames.put("cha", "Chamorro");
		mapOfLanguageCodesToNames.put("chb", "Chibcha");
		mapOfLanguageCodesToNames.put("che", "Chechen");
		mapOfLanguageCodesToNames.put("chg", "Chagatai");
		mapOfLanguageCodesToNames.put("chi", "Chinese");
		mapOfLanguageCodesToNames.put("zho", "Chinese");
		mapOfLanguageCodesToNames.put("chk", "Chuukese");
		mapOfLanguageCodesToNames.put("chm", "Mari (Russia)");
		mapOfLanguageCodesToNames.put("chn", "Chinook Jargon");
		mapOfLanguageCodesToNames.put("cho", "Choctaw");
		mapOfLanguageCodesToNames.put("chp", "Chipewyan, Dene Suline");
		mapOfLanguageCodesToNames.put("chr", "Cherokee");
		mapOfLanguageCodesToNames.put("chu", "Church Slavonic, Church Slavic, Old Church Slavonic, Old Slavonic, Old Bulgarian");
		mapOfLanguageCodesToNames.put("chv", "Chuvash");
		mapOfLanguageCodesToNames.put("chy", "Cheyenne");
		mapOfLanguageCodesToNames.put("cmc", "Chamic languages");
		mapOfLanguageCodesToNames.put("cop", "Coptic");
		mapOfLanguageCodesToNames.put("cor", "Cornish");
		mapOfLanguageCodesToNames.put("cos", "Corsican");
		mapOfLanguageCodesToNames.put("cpe", "creoles and pidgins, English-based");
		mapOfLanguageCodesToNames.put("cpf", "creoles and pidgins, French-based");
		mapOfLanguageCodesToNames.put("cpp", "creoles and pidgins, Portuguese-based");
		mapOfLanguageCodesToNames.put("cre", "Cree");
		mapOfLanguageCodesToNames.put("crh", "Crimean Tatar, Crimean Turkish");
		mapOfLanguageCodesToNames.put("crp", "creoles and pidgins");
		mapOfLanguageCodesToNames.put("csb", "Kashubian");
		mapOfLanguageCodesToNames.put("cus", "Cushitic languages");
		mapOfLanguageCodesToNames.put("cze", "Czech");
		mapOfLanguageCodesToNames.put("ces", "Czech");
		mapOfLanguageCodesToNames.put("dak", "Dakota");
		mapOfLanguageCodesToNames.put("dan", "Danish");
		mapOfLanguageCodesToNames.put("dar", "Dargwa");
		mapOfLanguageCodesToNames.put("day", "Land Dayak languages");
		mapOfLanguageCodesToNames.put("del", "Delaware");
		mapOfLanguageCodesToNames.put("den", "Slave (Athapascan)");
		mapOfLanguageCodesToNames.put("dgr", "Dogrib");
		mapOfLanguageCodesToNames.put("din", "Dinka");
		mapOfLanguageCodesToNames.put("div", "Divehi, Dhivehi, Maldivian");
		mapOfLanguageCodesToNames.put("doi", "Dogri");
		mapOfLanguageCodesToNames.put("dra", "Dravidian languages");
		mapOfLanguageCodesToNames.put("dsb", "Lower Sorbian");
		mapOfLanguageCodesToNames.put("dua", "Duala");
		mapOfLanguageCodesToNames.put("dum", "Dutch, Middle (c. 1050�1350)");
		mapOfLanguageCodesToNames.put("dut", "Dutch, Flemish");
		mapOfLanguageCodesToNames.put("nld", "Dutch, Flemish");
		mapOfLanguageCodesToNames.put("dyu", "Dyula");
		mapOfLanguageCodesToNames.put("dzo", "Dzongkha");
		mapOfLanguageCodesToNames.put("efi", "Efik");
		mapOfLanguageCodesToNames.put("egy", "Egyptian (Ancient)");
		mapOfLanguageCodesToNames.put("eka", "Ekajuk");
		mapOfLanguageCodesToNames.put("elx", "Elamite");
		mapOfLanguageCodesToNames.put("eng", "English");
		mapOfLanguageCodesToNames.put("enm", "Middle English (1100�1500)");
		mapOfLanguageCodesToNames.put("epo", "Esperanto");
		mapOfLanguageCodesToNames.put("est", "Estonian");
		mapOfLanguageCodesToNames.put("ewe", "Ewe");
		mapOfLanguageCodesToNames.put("ewo", "Ewondo");
		mapOfLanguageCodesToNames.put("fan", "Fang");
		mapOfLanguageCodesToNames.put("fao", "Faroese");
		mapOfLanguageCodesToNames.put("fat", "Fanti");
		mapOfLanguageCodesToNames.put("fij", "Fijian");
		mapOfLanguageCodesToNames.put("fil", "Filipino, Pilipino");
		mapOfLanguageCodesToNames.put("fin", "Finnish");
		mapOfLanguageCodesToNames.put("fiu", "Finno-Ugric languages");
		mapOfLanguageCodesToNames.put("fon", "Fon");
		mapOfLanguageCodesToNames.put("fre", "French");
		mapOfLanguageCodesToNames.put("fra", "French");
		mapOfLanguageCodesToNames.put("frm", "Middle French (c. 1400�1600)");
		mapOfLanguageCodesToNames.put("fro", "Old French (842�c. 1400)");
		mapOfLanguageCodesToNames.put("frr", "Northern Frisian");
		mapOfLanguageCodesToNames.put("frs", "Eastern Frisian");
		mapOfLanguageCodesToNames.put("fry", "Western Frisian");
		mapOfLanguageCodesToNames.put("ful", "Fulah");
		mapOfLanguageCodesToNames.put("fur", "Friulian");
		mapOfLanguageCodesToNames.put("gaa", "Ga");
		mapOfLanguageCodesToNames.put("gay", "Gayo");
		mapOfLanguageCodesToNames.put("gba", "Gbaya");
		mapOfLanguageCodesToNames.put("gem", "Germanic languages");
		mapOfLanguageCodesToNames.put("geo", "Georgian");
		mapOfLanguageCodesToNames.put("kat", "Georgian");
		mapOfLanguageCodesToNames.put("ger", "German");
		mapOfLanguageCodesToNames.put("deu", "German");
		mapOfLanguageCodesToNames.put("gez", "Ge'ez");
		mapOfLanguageCodesToNames.put("gil", "Gilbertese, Kiribati");
		mapOfLanguageCodesToNames.put("gla", "Scottish Gaelic, Gaelic");
		mapOfLanguageCodesToNames.put("gle", "Irish");
		mapOfLanguageCodesToNames.put("glg", "Galician");
		mapOfLanguageCodesToNames.put("glv", "Manx");
		mapOfLanguageCodesToNames.put("gmh", "Middle High German (ca. 1050�1500)");
		mapOfLanguageCodesToNames.put("goh", "Old High German (ca. 750�1050)");
		mapOfLanguageCodesToNames.put("gon", "Gondi");
		mapOfLanguageCodesToNames.put("gor", "Gorontalo");
		mapOfLanguageCodesToNames.put("got", "Gothic");
		mapOfLanguageCodesToNames.put("grb", "Grebo");
		mapOfLanguageCodesToNames.put("grc", "Ancient Greek (�1453)");
		mapOfLanguageCodesToNames.put("gre", "Modern Greek (1453�)");
		mapOfLanguageCodesToNames.put("ell", "Modern Greek (1453�)");
		mapOfLanguageCodesToNames.put("grn", "Guarani");
		mapOfLanguageCodesToNames.put("gsw", "Swiss German, Alemannic, Alsatian");
		mapOfLanguageCodesToNames.put("guj", "Gujarati");
		mapOfLanguageCodesToNames.put("gwi", "Gwich'in");
		mapOfLanguageCodesToNames.put("hai", "Haida");
		mapOfLanguageCodesToNames.put("hat", "Haitian Creole, Haitian");
		mapOfLanguageCodesToNames.put("hau", "Hausa");
		mapOfLanguageCodesToNames.put("haw", "Hawaiian");
		mapOfLanguageCodesToNames.put("heb", "Hebrew");
		mapOfLanguageCodesToNames.put("her", "Herero");
		mapOfLanguageCodesToNames.put("hil", "Hiligaynon");
		mapOfLanguageCodesToNames.put("him", "Himachali languages");
		mapOfLanguageCodesToNames.put("hin", "Hindi");
		mapOfLanguageCodesToNames.put("hit", "Hittite");
		mapOfLanguageCodesToNames.put("hmn", "Hmong");
		mapOfLanguageCodesToNames.put("hmo", "Hiri Motu");
		mapOfLanguageCodesToNames.put("hrv", "Croatian");
		mapOfLanguageCodesToNames.put("hsb", "Upper Sorbian");
		mapOfLanguageCodesToNames.put("hun", "Hungarian");
		mapOfLanguageCodesToNames.put("hup", "Hupa");
		mapOfLanguageCodesToNames.put("iba", "Iban");
		mapOfLanguageCodesToNames.put("ibo", "Igbo");
		mapOfLanguageCodesToNames.put("ice", "Icelandic");
		mapOfLanguageCodesToNames.put("isl", "Icelandic");
		mapOfLanguageCodesToNames.put("ido", "Ido");
		mapOfLanguageCodesToNames.put("iii", "Sichuan Yi, Nuosu");
		mapOfLanguageCodesToNames.put("ijo", "Ijo languages");
		mapOfLanguageCodesToNames.put("iku", "Inuktitut");
		mapOfLanguageCodesToNames.put("ile", "Interlingue, Occidental");
		mapOfLanguageCodesToNames.put("ilo", "Iloko");
		mapOfLanguageCodesToNames.put("ina", "Interlingua (International Auxiliary Language Association)");
		mapOfLanguageCodesToNames.put("inc", "Indic languages");
		mapOfLanguageCodesToNames.put("ind", "Indonesian");
		mapOfLanguageCodesToNames.put("ine", "Indo-European languages");
		mapOfLanguageCodesToNames.put("inh", "Ingush");
		mapOfLanguageCodesToNames.put("ipk", "Inupiaq");
		mapOfLanguageCodesToNames.put("ira", "Iranian languages");
		mapOfLanguageCodesToNames.put("iro", "Iroquoian languages");
		mapOfLanguageCodesToNames.put("ita", "Italian");
		mapOfLanguageCodesToNames.put("jav", "Javanese");
		mapOfLanguageCodesToNames.put("jbo", "Lojban");
		mapOfLanguageCodesToNames.put("jpn", "Japanese");
		mapOfLanguageCodesToNames.put("jpr", "Jud�o-Persian");
		mapOfLanguageCodesToNames.put("jrb", "Judeo-Arabic");
		mapOfLanguageCodesToNames.put("kaa", "Kara-Kalpak");
		mapOfLanguageCodesToNames.put("kab", "Kabyle");
		mapOfLanguageCodesToNames.put("kac", "Kachin, Jingpho");
		mapOfLanguageCodesToNames.put("kal", "Greenlandic, Kalaallisut");
		mapOfLanguageCodesToNames.put("kam", "Kamba");
		mapOfLanguageCodesToNames.put("kan", "Kannada");
		mapOfLanguageCodesToNames.put("kar", "Karen languages");
		mapOfLanguageCodesToNames.put("kas", "Kashmiri");
		mapOfLanguageCodesToNames.put("kau", "Kanuri");
		mapOfLanguageCodesToNames.put("kaw", "Kawi");
		mapOfLanguageCodesToNames.put("kaz", "Kazakh");
		mapOfLanguageCodesToNames.put("kbd", "Circassian");
		mapOfLanguageCodesToNames.put("kha", "Khasi");
		mapOfLanguageCodesToNames.put("khi", "Khoisan languages");
		mapOfLanguageCodesToNames.put("khm", "Central Khmer");
		mapOfLanguageCodesToNames.put("kho", "Khotanese, Sakan");
		mapOfLanguageCodesToNames.put("kik", "Kikuyu, Gikuyu");
		mapOfLanguageCodesToNames.put("kin", "Kinyarwanda");
		mapOfLanguageCodesToNames.put("kir", "Kirghiz, Kyrgyz");
		mapOfLanguageCodesToNames.put("kmb", "Kimbundu");
		mapOfLanguageCodesToNames.put("kok", "Konkani");
		mapOfLanguageCodesToNames.put("kom", "Komi");
		mapOfLanguageCodesToNames.put("kon", "Kongo");
		mapOfLanguageCodesToNames.put("kor", "Korean");
		mapOfLanguageCodesToNames.put("kos", "Kosraean");
		mapOfLanguageCodesToNames.put("kpe", "Kpelle");
		mapOfLanguageCodesToNames.put("krc", "Karachay-Balkar");
		mapOfLanguageCodesToNames.put("krl", "Karelian");
		mapOfLanguageCodesToNames.put("kro", "Kru languages");
		mapOfLanguageCodesToNames.put("kru", "Kurukh");
		mapOfLanguageCodesToNames.put("kua", "Kuanyama, Kwanyama");
		mapOfLanguageCodesToNames.put("kum", "Kumyk");
		mapOfLanguageCodesToNames.put("kur", "Kurdish");
		mapOfLanguageCodesToNames.put("kut", "Kutenai");
		mapOfLanguageCodesToNames.put("lad", "Ladino");
		mapOfLanguageCodesToNames.put("lah", "Lahnda");
		mapOfLanguageCodesToNames.put("lam", "Lamba");
		mapOfLanguageCodesToNames.put("lao", "Lao");
		mapOfLanguageCodesToNames.put("lat", "Latin");
		mapOfLanguageCodesToNames.put("lav", "Latvian");
		mapOfLanguageCodesToNames.put("lez", "Lezghian");
		mapOfLanguageCodesToNames.put("lim", "Limburgish, Limburger, Limburgan");
		mapOfLanguageCodesToNames.put("lin", "Lingala");
		mapOfLanguageCodesToNames.put("lit", "Lithuanian");
		mapOfLanguageCodesToNames.put("lol", "Mongo");
		mapOfLanguageCodesToNames.put("loz", "Lozi");
		mapOfLanguageCodesToNames.put("ltz", "Luxembourgish, Letzeburgesch");
		mapOfLanguageCodesToNames.put("lua", "Luba-Lulua");
		mapOfLanguageCodesToNames.put("lub", "Luba-Katanga");
		mapOfLanguageCodesToNames.put("lug", "Ganda");
		mapOfLanguageCodesToNames.put("lui", "Luise�o");
		mapOfLanguageCodesToNames.put("lun", "Lunda");
		mapOfLanguageCodesToNames.put("luo", "Luo (Kenya and Tanzania)");
		mapOfLanguageCodesToNames.put("lus", "Lushai");
		mapOfLanguageCodesToNames.put("mac", "Macedonian");
		mapOfLanguageCodesToNames.put("mkd", "Macedonian");
		mapOfLanguageCodesToNames.put("mad", "Madurese");
		mapOfLanguageCodesToNames.put("mag", "Magahi");
		mapOfLanguageCodesToNames.put("mah", "Marshallese");
		mapOfLanguageCodesToNames.put("mai", "Maithili");
		mapOfLanguageCodesToNames.put("mak", "Makasar");
		mapOfLanguageCodesToNames.put("mal", "Malayalam");
		mapOfLanguageCodesToNames.put("man", "Mandingo");
		mapOfLanguageCodesToNames.put("mao", "Maori");
		mapOfLanguageCodesToNames.put("mri", "Maori");
		mapOfLanguageCodesToNames.put("map", "Austronesian languages");
		mapOfLanguageCodesToNames.put("mar", "Marathi");
		mapOfLanguageCodesToNames.put("mas", "Maasai");
		mapOfLanguageCodesToNames.put("may", "Malay");
		mapOfLanguageCodesToNames.put("msa", "Malay");
		mapOfLanguageCodesToNames.put("mdf", "Moksha");
		mapOfLanguageCodesToNames.put("mdr", "Mandar");
		mapOfLanguageCodesToNames.put("men", "Mende");
		mapOfLanguageCodesToNames.put("mga", "Middle Irish (900�1200)");
		mapOfLanguageCodesToNames.put("mic", "Mi'kmaq, Micmac");
		mapOfLanguageCodesToNames.put("min", "Minangkabau");
		mapOfLanguageCodesToNames.put("mis", "Uncoded languages");
		mapOfLanguageCodesToNames.put("mkh", "Mon�Khmer languages");
		mapOfLanguageCodesToNames.put("mlg", "Malagasy");
		mapOfLanguageCodesToNames.put("mlt", "Maltese");
		mapOfLanguageCodesToNames.put("mnc", "Manchu");
		mapOfLanguageCodesToNames.put("mni", "Manipuri");
		mapOfLanguageCodesToNames.put("mno", "Manobo languages");
		mapOfLanguageCodesToNames.put("moh", "Mohawk");
		mapOfLanguageCodesToNames.put("mon", "Mongolian");
		mapOfLanguageCodesToNames.put("mos", "Mossi");
		mapOfLanguageCodesToNames.put("mul", "Multiple languages");
		mapOfLanguageCodesToNames.put("mun", "Munda languages");
		mapOfLanguageCodesToNames.put("mus", "Creek");
		mapOfLanguageCodesToNames.put("mwl", "Mirandese");
		mapOfLanguageCodesToNames.put("mwr", "Marwari");
		mapOfLanguageCodesToNames.put("myn", "Mayan languages");
		mapOfLanguageCodesToNames.put("myv", "Erzya");
		mapOfLanguageCodesToNames.put("nah", "Nahuatl");
		mapOfLanguageCodesToNames.put("nai", "North American Indian languages");
		mapOfLanguageCodesToNames.put("nap", "Neapolitan");
		mapOfLanguageCodesToNames.put("nau", "Nauruan");
		mapOfLanguageCodesToNames.put("nav", "Navajo, Navaho");
		mapOfLanguageCodesToNames.put("nbl", "Southern Ndebele");
		mapOfLanguageCodesToNames.put("nde", "Northern Ndebele");
		mapOfLanguageCodesToNames.put("ndo", "Ndonga");
		mapOfLanguageCodesToNames.put("nds", "Low German, Low Saxon");
		mapOfLanguageCodesToNames.put("nep", "Nepali");
		mapOfLanguageCodesToNames.put("new", "Nepal Bhasa, Newari");
		mapOfLanguageCodesToNames.put("nia", "Nias");
		mapOfLanguageCodesToNames.put("nic", "Niger�Congo languages");
		mapOfLanguageCodesToNames.put("niu", "Niuean");
		mapOfLanguageCodesToNames.put("nno", "Norwegian Nynorsk");
		mapOfLanguageCodesToNames.put("nob", "Norwegian Bokm�l");
		mapOfLanguageCodesToNames.put("nog", "Nogai");
		mapOfLanguageCodesToNames.put("non", "Old Norse");
		mapOfLanguageCodesToNames.put("nor", "Norwegian");
		mapOfLanguageCodesToNames.put("nqo", "N'Ko");
		mapOfLanguageCodesToNames.put("nso", "Northern Sotho, Pedi, Sepedi");
		mapOfLanguageCodesToNames.put("nub", "Nubian languages");
		mapOfLanguageCodesToNames.put("nwc", "Classical Newari, Old Newari, Classical Nepal Bhasa");
		mapOfLanguageCodesToNames.put("nya", "Chichewa, Chewa, Nyanja");
		mapOfLanguageCodesToNames.put("nym", "Nyamwezi");
		mapOfLanguageCodesToNames.put("nyn", "Nyankole");
		mapOfLanguageCodesToNames.put("nyo", "Nyoro");
		mapOfLanguageCodesToNames.put("nzi", "Nzima");
		mapOfLanguageCodesToNames.put("oci", "Occitan (1500�)");
		mapOfLanguageCodesToNames.put("oji", "Ojibwa");
		mapOfLanguageCodesToNames.put("ori", "Oriya");
		mapOfLanguageCodesToNames.put("orm", "Oromo");
		mapOfLanguageCodesToNames.put("osa", "Osage");
		mapOfLanguageCodesToNames.put("oss", "Ossetian, Ossetic");
		mapOfLanguageCodesToNames.put("ota", "Turkish, Ottoman (1500�1928)");
		mapOfLanguageCodesToNames.put("oto", "Otomian languages");
		mapOfLanguageCodesToNames.put("paa", "Papuan languages");
		mapOfLanguageCodesToNames.put("pag", "Pangasinan");
		mapOfLanguageCodesToNames.put("pal", "Pahlavi, (Middle Persian)");
		mapOfLanguageCodesToNames.put("pam", "Pampanga, Kapampangan");
		mapOfLanguageCodesToNames.put("pan", "Punjabi, Panjabi");
		mapOfLanguageCodesToNames.put("pap", "Papiamento");
		mapOfLanguageCodesToNames.put("pau", "Palauan");
		mapOfLanguageCodesToNames.put("peo", "Old Persian (ca. 600�400 BC)");
		mapOfLanguageCodesToNames.put("per", "Persian");
		mapOfLanguageCodesToNames.put("fas", "Persian");
		mapOfLanguageCodesToNames.put("phi", "Philippine languages");
		mapOfLanguageCodesToNames.put("phn", "Phoenician");
		mapOfLanguageCodesToNames.put("pli", "Pali");
		mapOfLanguageCodesToNames.put("pol", "Polish");
		mapOfLanguageCodesToNames.put("pon", "Pohnpeian");
		mapOfLanguageCodesToNames.put("por", "Portuguese");
		mapOfLanguageCodesToNames.put("pra", "Prakrit");
		mapOfLanguageCodesToNames.put("pro", "Old Proven�al, Old Occitan (�1500)");
		mapOfLanguageCodesToNames.put("pus", "Pashto language, Pashto");
		mapOfLanguageCodesToNames.put("qaa", "Reserved for local use");
		mapOfLanguageCodesToNames.put("qtz", "Reserved for local use");
		mapOfLanguageCodesToNames.put("que", "Quechua");
		mapOfLanguageCodesToNames.put("raj", "Rajasthani");
		mapOfLanguageCodesToNames.put("rap", "Rapanui");
		mapOfLanguageCodesToNames.put("rar", "Rarotongan, Cook Islands Maori");
		mapOfLanguageCodesToNames.put("roa", "Romance languages");
		mapOfLanguageCodesToNames.put("roh", "Romansh");
		mapOfLanguageCodesToNames.put("rom", "Romany");
		mapOfLanguageCodesToNames.put("rum", "Romanian");
		mapOfLanguageCodesToNames.put("ron", "Romanian");
		mapOfLanguageCodesToNames.put("run", "Rundi");
		mapOfLanguageCodesToNames.put("rup", "Aromanian, Arumanian, Macedo-Romanian");
		mapOfLanguageCodesToNames.put("rus", "Russian");
		mapOfLanguageCodesToNames.put("sad", "Sandawe");
		mapOfLanguageCodesToNames.put("sag", "Sango");
		mapOfLanguageCodesToNames.put("sah", "Yakut");
		mapOfLanguageCodesToNames.put("sai", "South American Indian languages");
		mapOfLanguageCodesToNames.put("sal", "Salishan languages");
		mapOfLanguageCodesToNames.put("sam", "Samaritan Aramaic");
		mapOfLanguageCodesToNames.put("san", "Sanskrit");
		mapOfLanguageCodesToNames.put("sas", "Sasak");
		mapOfLanguageCodesToNames.put("sat", "Santali");
		mapOfLanguageCodesToNames.put("scn", "Sicilian");
		mapOfLanguageCodesToNames.put("sco", "Scots");
		mapOfLanguageCodesToNames.put("sel", "Selkup");
		mapOfLanguageCodesToNames.put("sem", "Semitic languages");
		mapOfLanguageCodesToNames.put("sga", "Old Irish (to 900)");
		mapOfLanguageCodesToNames.put("sgn", "Sign languages");
		mapOfLanguageCodesToNames.put("shn", "Shan");
		mapOfLanguageCodesToNames.put("sid", "Sidamo");
		mapOfLanguageCodesToNames.put("sin", "Sinhalese, Sinhala");
		mapOfLanguageCodesToNames.put("sio", "Siouan languages");
		mapOfLanguageCodesToNames.put("sit", "Sino-Tibetan languages");
		mapOfLanguageCodesToNames.put("sla", "Slavic languages");
		mapOfLanguageCodesToNames.put("slo", "Slovak");
		mapOfLanguageCodesToNames.put("slk", "Slovak");
		mapOfLanguageCodesToNames.put("slv", "Slovenian");
		mapOfLanguageCodesToNames.put("sma", "Southern Sami");
		mapOfLanguageCodesToNames.put("sme", "Northern Sami");
		mapOfLanguageCodesToNames.put("smi", "Sami languages");
		mapOfLanguageCodesToNames.put("smj", "Lule Sami");
		mapOfLanguageCodesToNames.put("smn", "Inari Sami");
		mapOfLanguageCodesToNames.put("smo", "Samoan");
		mapOfLanguageCodesToNames.put("sms", "Skolt Sami");
		mapOfLanguageCodesToNames.put("sna", "Shona");
		mapOfLanguageCodesToNames.put("snd", "Sindhi");
		mapOfLanguageCodesToNames.put("snk", "Soninke");
		mapOfLanguageCodesToNames.put("sog", "Sogdian");
		mapOfLanguageCodesToNames.put("som", "Somali");
		mapOfLanguageCodesToNames.put("son", "Songhay languages");
		mapOfLanguageCodesToNames.put("sot", "Southern Sotho");
		mapOfLanguageCodesToNames.put("spa", "Spanish, Castilian");
		mapOfLanguageCodesToNames.put("srd", "Sardinian");
		mapOfLanguageCodesToNames.put("srn", "Sranan Tongo");
		mapOfLanguageCodesToNames.put("srp", "Serbian");
		mapOfLanguageCodesToNames.put("srr", "Serer");
		mapOfLanguageCodesToNames.put("ssa", "Nilo-Saharan languages");
		mapOfLanguageCodesToNames.put("ssw", "Swati");
		mapOfLanguageCodesToNames.put("suk", "Sukuma");
		mapOfLanguageCodesToNames.put("sun", "Sundanese");
		mapOfLanguageCodesToNames.put("sus", "Susu");
		mapOfLanguageCodesToNames.put("sux", "Sumerian");
		mapOfLanguageCodesToNames.put("swa", "Swahili");
		mapOfLanguageCodesToNames.put("swe", "Swedish");
		mapOfLanguageCodesToNames.put("syc", "Classical Syriac");
		mapOfLanguageCodesToNames.put("syr", "Syriac (Northeastern Neo-Aramaic)");
		mapOfLanguageCodesToNames.put("tah", "Tahitian");
		mapOfLanguageCodesToNames.put("tai", "Tai languages");
		mapOfLanguageCodesToNames.put("tam", "Tamil");
		mapOfLanguageCodesToNames.put("tat", "Tatar");
		mapOfLanguageCodesToNames.put("tel", "Telugu");
		mapOfLanguageCodesToNames.put("tem", "Time");
		mapOfLanguageCodesToNames.put("ter", "Tereno");
		mapOfLanguageCodesToNames.put("tet", "Tetum");
		mapOfLanguageCodesToNames.put("tgk", "Tajik");
		mapOfLanguageCodesToNames.put("tgl", "Tagalog");
		mapOfLanguageCodesToNames.put("tha", "Thai");
		mapOfLanguageCodesToNames.put("tib", "Tibetan");
		mapOfLanguageCodesToNames.put("bod", "Tibetan");
		mapOfLanguageCodesToNames.put("tig", "Tigre");
		mapOfLanguageCodesToNames.put("tir", "Tigrinya");
		mapOfLanguageCodesToNames.put("tiv", "Tiv");
		mapOfLanguageCodesToNames.put("tkl", "Tokelau");
		mapOfLanguageCodesToNames.put("tlh", "Klingon, tlhIngan-Hol");
		mapOfLanguageCodesToNames.put("tli", "Tlingit");
		mapOfLanguageCodesToNames.put("tmh", "Tamashek");
		mapOfLanguageCodesToNames.put("tog", "Tonga (Nyasa)");
		mapOfLanguageCodesToNames.put("ton", "Tonga (Tonga Islands)");
		mapOfLanguageCodesToNames.put("tpi", "Tok Pisin");
		mapOfLanguageCodesToNames.put("tsi", "Tsimshian");
		mapOfLanguageCodesToNames.put("tsn", "Tswana");
		mapOfLanguageCodesToNames.put("tso", "Tsonga");
		mapOfLanguageCodesToNames.put("tuk", "Turkmen");
		mapOfLanguageCodesToNames.put("tum", "Tumbuka");
		mapOfLanguageCodesToNames.put("tup", "Tupian languages");
		mapOfLanguageCodesToNames.put("tur", "Turkish");
		mapOfLanguageCodesToNames.put("tut", "Altaic languages");
		mapOfLanguageCodesToNames.put("tvl", "Tuvalu");
		mapOfLanguageCodesToNames.put("twi", "Twi");
		mapOfLanguageCodesToNames.put("tyv", "Tuvinian");
		mapOfLanguageCodesToNames.put("udm", "Udmurt");
		mapOfLanguageCodesToNames.put("uga", "Ugaritic");
		mapOfLanguageCodesToNames.put("uig", "Uighur, Uyghur");
		mapOfLanguageCodesToNames.put("ukr", "Ukrainian");
		mapOfLanguageCodesToNames.put("umb", "Umbundu");
		mapOfLanguageCodesToNames.put("und", "Undetermined language");
		mapOfLanguageCodesToNames.put("urd", "Urdu");
		mapOfLanguageCodesToNames.put("uzb", "Uzbek");
		mapOfLanguageCodesToNames.put("vai", "Vai");
		mapOfLanguageCodesToNames.put("ven", "Venda");
		mapOfLanguageCodesToNames.put("vie", "Vietnamese");
		mapOfLanguageCodesToNames.put("vol", "Volap�k");
		mapOfLanguageCodesToNames.put("vot", "Votic");
		mapOfLanguageCodesToNames.put("wak", "Wakashan languages");
		mapOfLanguageCodesToNames.put("wal", "Wolaytta, Wolaitta");
		mapOfLanguageCodesToNames.put("war", "Waray-Waray");
		mapOfLanguageCodesToNames.put("was", "Washo");
		mapOfLanguageCodesToNames.put("wel", "Welsh");
		mapOfLanguageCodesToNames.put("cym", "Welsh");
		mapOfLanguageCodesToNames.put("wen", "Sorbian languages");
		mapOfLanguageCodesToNames.put("wln", "Walloon");
		mapOfLanguageCodesToNames.put("wol", "Wolof");
		mapOfLanguageCodesToNames.put("xal", "Kalmyk, Oirat");
		mapOfLanguageCodesToNames.put("xho", "Xhosa");
		mapOfLanguageCodesToNames.put("yao", "Yao");
		mapOfLanguageCodesToNames.put("yap", "Yapese");
		mapOfLanguageCodesToNames.put("yid", "Yiddish");
		mapOfLanguageCodesToNames.put("yor", "Yoruba");
		mapOfLanguageCodesToNames.put("ypk", "Yupik languages");
		mapOfLanguageCodesToNames.put("zap", "Zapotec");
		mapOfLanguageCodesToNames.put("zbl", "Blissymbols, Blissymbolics, Bliss");
		mapOfLanguageCodesToNames.put("zen", "Zenaga");
		mapOfLanguageCodesToNames.put("zha", "Zhuang, Chuang");
		mapOfLanguageCodesToNames.put("znd", "Zande languages");
		mapOfLanguageCodesToNames.put("zul", "Zulu");
		mapOfLanguageCodesToNames.put("zun", "Zuni");
		mapOfLanguageCodesToNames.put("zxx", "No linguistic content; not applicable");
		mapOfLanguageCodesToNames.put("zza", "Zaza, Dimili, Dimli, Kirdki, Kirmanjki, Zazaki");
	}

	public boolean isValidLanguageCode(final String languageCode) {
		return mapOfLanguageCodesToNames.containsKey(languageCode);
	}

}
